name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main # or your default branch like master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r Automated_AI_Instagram/requirements.txt

      - name: Run tests
        run: python -m pytest tests
        working-directory: Automated_AI_Instagram
